"""Typed output models for the agent.

Pydantic-AI validates the LLM's free text against these schemas and
self-repairs on failure (feeds the validation error back and retries), so the
app never sees malformed structure from the model.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class TopicSpec(BaseModel):
    name: str = Field(description="Topic name")
    description: str = Field(default="", description="One-sentence description")


class ModuleSpec(BaseModel):
    module: str = Field(description="Module name")
    topics: list[TopicSpec] = Field(description="Topics in this module")


class SyllabusStructure(BaseModel):
    """Result of parsing a syllabus into modules + topics."""
    modules: list[ModuleSpec]


class TaggingResult(BaseModel):
    """topic_id -> [passage_ids]. Each passage appears in exactly one topic's
    list; passages that match no topic are omitted entirely."""
    assignments: dict[int, list[int]]


class GeneratedQuestion(BaseModel):
    """One question generated by the LLM, grounded in a topic's passages."""
    text: str
    type: str = Field(default="short_answer", description="mcq | short_answer | explain")
    expected_key_points: list[str] = Field(default_factory=list)


class GeneratedQuestions(BaseModel):
    """A batch of questions."""
    questions: list[GeneratedQuestion]


class AnswerEvaluation(BaseModel):
    """LLM's judgment of a user's answer against expected key points."""
    score: float = Field(ge=0.0, le=1.0)
    feedback: str = Field(default="")
    matched_key_points: list[str] = Field(default_factory=list)
    missed_key_points: list[str] = Field(default_factory=list)
